---
################################################################################
#
#   CONFIGURATIONS
#
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
IPs:
  node0: 192.168.1.2
  node1: 192.168.1.3
  node2: 192.168.1.4
  node3: 192.168.1.5
expectation: 1.0
log_level: 3
peers_p2p_port:
  node0: 9000
  node1: 9000
  node2: 9000
  node3: 9000
rpc_listen_port: 9500
max_pool: 30
batch_size: 5000
bgnodes: 0
round: 500
protocol: bit