- hosts: bit
  remote_user: vagrant
  tasks:
    - name: copy configuration file
      copy:
        src: /vagrant/BitFT/config_gen/{{inventory_hostname}}_{{item}}.yaml
        dest: /home/vagrant/BitFT{{item}}/config.yaml
      loop:
        - 0
      when: ansible_hostname is not match "node1"

    - name: copy configuration file
      copy:
        src: /vagrant/BitFT/config_gen/{{inventory_hostname}}_{{item}}.yaml
        dest: /home/vagrant/BitFT{{item}}/config.yaml
      loop:
        - 0
      when: (ansible_hostname is match "node1")