- hosts: bit
  remote_user: vagrant
  tasks:
    - name: clone BitFT
      copy:
        src: /vagrant/BitFT/BitFT
        dest: /home/vagrant/BitFT{{item}}/
      loop:
        - 0
      when: (ansible_hostname is not match "node1")

    - name: clone BitFT
      copy:
        src: /vagrant/BitFT/BitFT
        dest: /home/vagrant/BitFT{{item}}/
      loop:
        - 0
      when: (ansible_hostname is match "node1")

    - name: chmod BitFT
      shell: chmod +x /home/vagrant/BitFT{{item}}/BitFT
      loop:
        - 0
      when: (ansible_hostname is not match "node1")

    - name: chmod BitFT
      shell: chmod +x /home/vagrant/BitFT{{item}}/BitFT
      loop:
        - 0
      when: (ansible_hostname is match "node1")