- hosts: bit
  remote_user: vagrant
  tasks:
    - name: fetch the results
      fetch:
        src: /home/vagrant/testbed/{{inventory_hostname}}_{{item}}.txt
        dest: /vagrant/result/
      loop:
        - 0
      when: (ansible_hostname is not match "node1")

    - name: fetch the results
      fetch:
        src: /home/vagrant/testbed/{{inventory_hostname}}_{{item}}.txt
        dest: /vagrant/result/
      loop:
        - 0
      when: (ansible_hostname is match "node1")

