- hosts: bit
  remote_user: vagrant
  tasks:
    - name: create user
      user:
        name: "{{ item.user }}"
        password: "{{ item.pass | password_hash('sha512')}}"    #采用哈希加密
        state: present
      loop:
        - { user: hh, pass: hh}
