- hosts: bit
  remote_user: vagrant
  tasks:
    - name: delete the bit directory
      shell: rm -rf /home/vagrant/BitFT{{item}}
      loop:
        - 0
      when: (ansible_hostname is not match "node1")

    - name: delete the bit directory
      shell: rm -rf /home/vagrant/BitFT{{item}}
      loop:
        - 0
      when: (ansible_hostname is match "node1")

    - name: clean the testbed directory
      shell: rm -rf /home/vagrant/testbed